// Package service contains the business logic for TeslaGo.
//
// The service layer sits between the HTTP handlers and the repository/database.
// Its responsibilities:
//   - Orchestrate multi-step operations (e.g. exchange code → encrypt → save → sync vehicles)
//   - Enforce business rules (e.g. only one Tesla account per admin)
//   - Manage the OAuth token lifecycle (refresh when expired)
//   - Keep handlers and repositories thin and focused
//
// Clean Architecture rule: the service imports the repository interface and
// models, but knows NOTHING about HTTP, JSON, or GORM specifics.
//
// tesla_auth_service.go — OAuth 2.0 + PKCE flow for Tesla account linking.
//
// The complete flow this service orchestrates:
//
//  1. Admin calls GET /tesla/auth/url
//     → BuildAuthURL() returns a Tesla login URL
//
//  2. Admin is redirected to Tesla, logs in, and approves access
//     → Tesla redirects to GET /tesla/auth/callback?code=xxx&state=yyy
//
//  3. HandleCallback() is called:
//     a. Calls Tesla API to exchange the code for tokens (ExchangeAuthCode)
//     b. Encrypts both tokens with AES-256-GCM
//     c. Saves the TeslaUser record to PostgreSQL (upsert)
//     d. Fetches the admin's vehicles from Tesla
//     e. Saves each vehicle to PostgreSQL (upsert)
//
//  4. Later calls use GetValidAccessToken() which:
//     a. Loads the TeslaUser from DB
//     b. Checks if the access token is near expiry
//     c. If yes: calls Tesla to refresh, saves new tokens, returns new token
//     d. If no:  just decrypts and returns the stored token
package service

import (
	"context"
	"fmt"
	"net/url"
	"time"

	extTesla "github.com/tomyogms/TeslaGo/external/tesla"
	"github.com/tomyogms/TeslaGo/internal/model"
	"github.com/tomyogms/TeslaGo/internal/repository"
)

// TeslaAuthService is the interface that handlers depend on.
// Defining an interface (rather than importing the concrete struct) means:
//   - Tests can inject a mock implementation (no real DB or HTTP needed)
//   - We could swap the implementation (e.g. different OAuth provider) without
//     changing a single line of handler code
type TeslaAuthService interface {
	// BuildAuthURL constructs the Tesla OAuth authorization URL with PKCE params.
	// The admin should be redirected to this URL in their browser.
	// state and codeChallenge are generated by the handler (see tesla_auth_handler.go).
	BuildAuthURL(state, codeChallenge string) string

	// HandleCallback completes the OAuth flow after Tesla redirects back.
	// It exchanges the code for tokens, encrypts them, saves them, and syncs vehicles.
	HandleCallback(ctx context.Context, adminID, code, codeVerifier string) (*model.TeslaUser, error)

	// GetVehicles returns all Tesla vehicles stored in our DB for the given admin.
	// Note: this reads from our database, not from the Tesla API directly.
	GetVehicles(ctx context.Context, adminID string) ([]model.TeslaVehicle, error)

	// GetValidAccessToken returns a ready-to-use (decrypted, non-expired) access
	// token for the given admin. Automatically refreshes if near expiry.
	GetValidAccessToken(ctx context.Context, adminID string) (string, error)
}

// teslaAuthService is the private concrete struct that implements TeslaAuthService.
// All fields are injected via the constructor — the struct never creates its own dependencies.
type teslaAuthService struct {
	// repo is the database layer for reading/writing TeslaUser and TeslaVehicle rows.
	repo repository.TeslaRepository

	// teslaClient is the HTTP client for talking to Tesla's OAuth and Owner APIs.
	// Using an interface here (TeslaAPIClient below) means tests can inject a mock.
	teslaClient TeslaAPIClient

	// clientID is the Tesla OAuth app client ID (from TESLA_CLIENT_ID env var).
	clientID string

	// redirectURI must match exactly what was registered in the Tesla developer portal.
	// Tesla will reject the token exchange if it doesn't match.
	redirectURI string

	// authBaseURL is the base URL for Tesla's auth server (https://auth.tesla.com).
	authBaseURL string

	// tokenSecret is the AES-256 encryption key (from TESLA_TOKEN_SECRET env var).
	// Used to encrypt/decrypt tokens before storing them in the database.
	tokenSecret string
}

// TeslaAPIClient is an interface wrapping all the external Tesla API calls the
// service needs. Defining it here (not in the external/tesla package) follows
// the Go convention: "accept interfaces, return structs" — the consumer defines
// the interface it needs, the provider satisfies it.
//
// This is the key to making the service fully testable without real HTTP calls:
// tests inject a mockTeslaAPIClient that returns canned responses.
type TeslaAPIClient interface {
	ExchangeAuthCode(authBaseURL, clientID, code, codeVerifier, redirectURI string) (*extTesla.TokenResponse, error)
	RefreshToken(authBaseURL, clientID, refreshToken string) (*extTesla.TokenResponse, error)
	GetVehicles(accessToken string) ([]extTesla.Vehicle, error)
}

// NewTeslaAuthService is the constructor (factory function).
// It accepts all dependencies as arguments and returns the TeslaAuthService
// interface — callers never see the concrete struct.
//
// This pattern is called Dependency Injection: dependencies are "injected"
// from the outside rather than created internally. It makes testing easy and
// keeps components loosely coupled.
func NewTeslaAuthService(
	repo repository.TeslaRepository,
	teslaClient TeslaAPIClient,
	clientID, redirectURI, authBaseURL, tokenSecret string,
) TeslaAuthService {
	return &teslaAuthService{
		repo:        repo,
		teslaClient: teslaClient,
		clientID:    clientID,
		redirectURI: redirectURI,
		authBaseURL: authBaseURL,
		tokenSecret: tokenSecret,
	}
}

// BuildAuthURL constructs the full Tesla OAuth 2.0 authorization URL.
//
// The resulting URL looks like:
//
//	https://auth.tesla.com/oauth2/v3/authorize
//	  ?client_id=ownerapi
//	  &redirect_uri=http://localhost:8080/tesla/auth/callback
//	  &response_type=code
//	  &scope=openid+email+offline_access
//	  &state=<random>.<adminID>
//	  &code_challenge=<base64url(SHA256(verifier))>
//	  &code_challenge_method=S256
//
// When the admin visits this URL, Tesla shows a login page. After they log in
// and approve, Tesla redirects their browser to redirect_uri with a `code` param.
func (s *teslaAuthService) BuildAuthURL(state, codeChallenge string) string {
	// url.Values is Go's standard way to build URL query strings safely.
	// It handles URL-encoding of special characters automatically.
	params := url.Values{}
	params.Set("client_id", s.clientID)
	params.Set("redirect_uri", s.redirectURI)
	params.Set("response_type", "code")                // we want an auth code, not a token directly
	params.Set("scope", "openid email offline_access") // offline_access = we get a refresh token
	params.Set("state", state)                         // CSRF + admin_id carrier
	params.Set("code_challenge", codeChallenge)        // PKCE challenge
	params.Set("code_challenge_method", "S256")        // SHA-256 method

	return s.authBaseURL + "/oauth2/v3/authorize?" + params.Encode()
}

// HandleCallback is called when Tesla redirects the admin back to our app.
// It performs steps 3a–3e of the OAuth flow described in the package doc.
//
// Error handling philosophy: if the token exchange or save fails we return an
// error immediately — the admin must retry the whole flow. Vehicle sync failure
// is non-fatal (best-effort) because we can sync again later.
func (s *teslaAuthService) HandleCallback(ctx context.Context, adminID, code, codeVerifier string) (*model.TeslaUser, error) {
	// Step 3a: Exchange the one-time authorization code for access + refresh tokens.
	// The codeVerifier proves we are the same party that initiated the flow (PKCE).
	tokenResp, err := s.teslaClient.ExchangeAuthCode(s.authBaseURL, s.clientID, code, codeVerifier, s.redirectURI)
	if err != nil {
		return nil, fmt.Errorf("exchanging auth code: %w", err)
	}

	// Step 3b: Encrypt both tokens before saving. NEVER store plain-text tokens.
	encAccessToken, err := extTesla.Encrypt(tokenResp.AccessToken, s.tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("encrypting access token: %w", err)
	}

	encRefreshToken, err := extTesla.Encrypt(tokenResp.RefreshToken, s.tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("encrypting refresh token: %w", err)
	}

	// Build the TeslaUser struct to persist.
	// TokenExpiresAt is computed from "now + ExpiresIn seconds" so we know
	// exactly when to refresh without making an extra API call.
	teslaUser := &model.TeslaUser{
		AdminID:        adminID,
		AccessToken:    encAccessToken,
		RefreshToken:   encRefreshToken,
		TokenExpiresAt: time.Now().UTC().Add(time.Duration(tokenResp.ExpiresIn) * time.Second),
	}

	// Step 3c: Save (upsert) the TeslaUser to the database.
	if err := s.repo.UpsertTeslaUser(ctx, teslaUser); err != nil {
		return nil, fmt.Errorf("saving tesla user: %w", err)
	}

	// Steps 3d–3e: Sync vehicles — best effort.
	// We use the plain-text access token (before encrypting it again) to
	// immediately fetch the admin's vehicles while the token is fresh.
	// If this fails we log it but don't fail the whole auth flow — the admin
	// is still linked successfully and can retry vehicle sync later.
	_ = s.syncVehicles(ctx, teslaUser, tokenResp.AccessToken)

	return teslaUser, nil
}

// GetVehicles returns all Tesla vehicles stored in our database for the admin.
// It does NOT call the Tesla API — it reads from our local database.
//
// This is intentional: we don't want to make a live Tesla API call on every
// GET /tesla/vehicles request. The vehicle list is synced during the OAuth
// callback and can be re-synced explicitly if needed.
func (s *teslaAuthService) GetVehicles(ctx context.Context, adminID string) ([]model.TeslaVehicle, error) {
	// First, look up the TeslaUser to get its internal database ID.
	// (We need the ID to query vehicles by foreign key.)
	teslaUser, err := s.repo.GetTeslaUserByAdminID(ctx, adminID)
	if err != nil {
		return nil, fmt.Errorf("getting tesla user: %w", err)
	}

	// Then fetch all vehicles linked to that TeslaUser's ID.
	vehicles, err := s.repo.GetVehiclesByTeslaUserID(ctx, teslaUser.ID)
	if err != nil {
		return nil, fmt.Errorf("getting vehicles: %w", err)
	}

	return vehicles, nil
}

// GetValidAccessToken returns a decrypted, non-expired access token for the admin.
//
// This is the central method for token lifecycle management. The battery and
// charging services (Phase 2) will call this before every Tesla API request.
//
// The 5-minute buffer:
//   - We refresh when the token is within 5 minutes of expiry.
//   - This prevents the race condition where the token expires between us
//     checking it and actually using it in the next API call.
func (s *teslaAuthService) GetValidAccessToken(ctx context.Context, adminID string) (string, error) {
	teslaUser, err := s.repo.GetTeslaUserByAdminID(ctx, adminID)
	if err != nil {
		return "", fmt.Errorf("getting tesla user: %w", err)
	}

	// Check if the token is expired or will expire within 5 minutes.
	// time.Now().UTC().After(expiresAt - 5min) means "is now past (expiry - 5min)?"
	if time.Now().UTC().After(teslaUser.TokenExpiresAt.Add(-5 * time.Minute)) {
		// Token is stale — refresh it and persist the new tokens.
		teslaUser, err = s.refreshAndPersistToken(ctx, teslaUser)
		if err != nil {
			return "", fmt.Errorf("refreshing token: %w", err)
		}
	}

	// Decrypt the stored access token and return the plain-text value.
	plainAccessToken, err := extTesla.Decrypt(teslaUser.AccessToken, s.tokenSecret)
	if err != nil {
		return "", fmt.Errorf("decrypting access token: %w", err)
	}

	return plainAccessToken, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helper methods
// ─────────────────────────────────────────────────────────────────────────────

// refreshAndPersistToken calls the Tesla refresh endpoint, encrypts the new
// tokens, and saves them to the database. It returns the updated TeslaUser.
//
// Note: Tesla rotates the refresh token on every refresh — the old one becomes
// invalid. Always save the NEW refresh token immediately.
func (s *teslaAuthService) refreshAndPersistToken(ctx context.Context, teslaUser *model.TeslaUser) (*model.TeslaUser, error) {
	// Decrypt the stored refresh token so we can send it to Tesla.
	plainRefreshToken, err := extTesla.Decrypt(teslaUser.RefreshToken, s.tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("decrypting refresh token: %w", err)
	}

	// Call Tesla's token endpoint with grant_type=refresh_token.
	tokenResp, err := s.teslaClient.RefreshToken(s.authBaseURL, s.clientID, plainRefreshToken)
	if err != nil {
		return nil, fmt.Errorf("calling tesla refresh: %w", err)
	}

	// Encrypt the brand-new tokens before saving.
	encAccessToken, err := extTesla.Encrypt(tokenResp.AccessToken, s.tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("encrypting new access token: %w", err)
	}

	encRefreshToken, err := extTesla.Encrypt(tokenResp.RefreshToken, s.tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("encrypting new refresh token: %w", err)
	}

	// Update the in-memory struct and persist to DB.
	teslaUser.AccessToken = encAccessToken
	teslaUser.RefreshToken = encRefreshToken
	teslaUser.TokenExpiresAt = time.Now().UTC().Add(time.Duration(tokenResp.ExpiresIn) * time.Second)

	if err := s.repo.UpsertTeslaUser(ctx, teslaUser); err != nil {
		return nil, fmt.Errorf("saving refreshed tesla user: %w", err)
	}

	return teslaUser, nil
}

// syncVehicles fetches the list of vehicles from the Tesla API and upserts
// each one into our database.
//
// This is called right after a successful OAuth callback while we still have
// the plain-text access token available. It is best-effort — errors are
// returned but the caller (HandleCallback) ignores them.
func (s *teslaAuthService) syncVehicles(ctx context.Context, teslaUser *model.TeslaUser, plainAccessToken string) error {
	// Ask Tesla for all vehicles on this account.
	vehicles, err := s.teslaClient.GetVehicles(plainAccessToken)
	if err != nil {
		return fmt.Errorf("fetching vehicles from tesla: %w", err)
	}

	// Save each vehicle, creating a new row or updating the existing one.
	for _, v := range vehicles {
		vehicle := &model.TeslaVehicle{
			TeslaUserID: teslaUser.ID,
			VehicleID:   v.ID, // Tesla's Owner API ID (use for API calls)
			DisplayName: v.DisplayName,
			VIN:         v.VIN,
			State:       v.State, // online / asleep / offline
		}
		if err := s.repo.UpsertTeslaVehicle(ctx, vehicle); err != nil {
			return fmt.Errorf("upserting vehicle %d: %w", v.ID, err)
		}
	}

	return nil
}
